In [2]:
import pandas as pd
import sqlalchemy as sa

# 1. Ruta de tu archivo Excel
excel_path = r"C:\Users\faust\Desktop\Personal\Cursos\Curso PBI\Proyectos\Dataset - Prueba.xlsx"

# Leer las hojas del Excel
df_ventas = pd.read_excel(excel_path, sheet_name="Ventas")
df_gastos = pd.read_excel(excel_path, sheet_name="Gastos")

print("--- Vista previa de Ventas ---")
display(df_ventas.head(3))

print("--- Vista previa de Gastos ---")
display(df_gastos.head(3))

--- Vista previa de Ventas ---

,Fecha,Pais Destino,Ciudad de envio,Zona seguimiento,latitud,longitud,Vendedor,Categoria Venta,Articulo Venta,Cantidad vendida,Meta Cantidad,Precio unitario,Total Ventas
0,2019-11-18,Brasil,Bogota,"Chapinero, bogotá",4.698636,-74.142084,Carlos,Aseo,Trapero,7,10,1.40,14.00
1,2019-03-12,España,Cali,"Usaquen, bogotá",4.692309,-74.131391,David,Oficina,Set de boligrafos,19,55,12.49,686.95
2,2018-07-07,México,Medellin,"Usme, bogotá",4.689440,-74.132599,Carolina,Aseo,Cera,4,5,1.70,8.50

--- Vista previa de Gastos ---

       Fecha   Oficina Concepto Gasto  Total Gastos
0 2019-08-03    Bogota        Energia          1584
1 2018-06-03      Cali       Arriendo           213
2 2018-11-11  Medellin       Telefono          1138

In [3]:
# Configuración del servidor SQL local
server = 'XAVIER-PC'
database = 'GlobalSalesDB'

# Crear el motor de conexión usando autenticación de Windows
connection_string = f"mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
engine = sa.create_engine(connection_string)

# Guardar los DataFrames de Pandas como tablas relacionales en SQL Server
df_ventas.to_sql('Fact_Ventas', con=engine, if_exists='replace', index=False)
df_gastos.to_sql('Dim_Gastos', con=engine, if_exists='replace', index=False)

print("¡Tablas 'Fact_Ventas' y 'Dim_Gastos' creadas y cargadas con éxito en SQL Server!")

¡Tablas 'Fact_Ventas' y 'Dim_Gastos' creadas y cargadas con éxito en SQL Server!